name: Test and coverage
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run test
        run: make test
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
